stages:
  - build
  - test
  - run

variables:
  KUBE_NAMESPACE: "ecommerce"

# 🧱 Build all docker images
build-images:
  stage: build
  image: docker:25.0.3
  services:
    - docker:25.0.3-dind
  script:
    - docker build -t extractor:ci ./extractor
    - docker build -t loader:ci ./loader
    - docker build -t dbt-runner:ci ./dbt-runner
    - docker build -t exporter:ci ./exporter
  only:
    - main

# 🧪 Run dbt tests (locally inside GitLab runner)
dbt-tests:
  stage: test
  image: python:3.11-slim
  before_script:
    - pip install dbt-postgres==1.8.6
    - cd dbt-runner
  script:
    - DBT_PROFILES_DIR=. dbt deps
    - DBT_PROFILES_DIR=. dbt compile
    - DBT_PROFILES_DIR=. dbt test --select tag:critical || true
  only:
    - main

# 🚀 Run dbt job inside Kubernetes
run-dbt:
  stage: run
  image: bitnami/kubectl:1.30
  script:
    - kubectl create configmap dbt-profiles \
        --from-file=profiles.yml=./dbt-runner/profiles.yml \
        -n $KUBE_NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
    - JOB=$(kubectl create -n $KUBE_NAMESPACE -f K8s/dbt-job.yaml -o jsonpath='{.metadata.name}')
    - echo "Running $JOB"
    - kubectl wait -n $KUBE_NAMESPACE --for=condition=ready pod -l job-name=$JOB --timeout=180s || true
    - kubectl logs -n $KUBE_NAMESPACE -l job-name=$JOB --tail=200
    - kubectl wait -n $KUBE_NAMESPACE --for=condition=complete job/$JOB --timeout=1800s
  only:
    - main
