apiVersion: batch/v1
kind: Job
metadata:
  name: exporter-job
  namespace: ecommerce
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: exporter
          image: exporter:0.1
          env:
            - name: MINIO_ENDPOINT
              value: minio.ecommerce.svc.cluster.local:9000
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: MINIO_ROOT_USER
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_BUCKET
              value: ecommerce
            - name: CURATED_PREFIX
              value: curated
            - name: PG_HOST
              value: postgres.ecommerce.svc.cluster.local
            - name: PG_DB
              valueFrom: { secretKeyRef: { name: postgres-secrets, key: POSTGRES_DB } }
            - name: PG_USER
              valueFrom: { secretKeyRef: { name: postgres-secrets, key: POSTGRES_USER } }
            - name: PG_PASS
              valueFrom: { secretKeyRef: { name: postgres-secrets, key: POSTGRES_PASSWORD } }
