apiVersion: batch/v1
kind: Job
metadata:
  generateName: extractor-job-
  namespace: ecommerce
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: extractor
          image: extractor:0.2
          imagePullPolicy: IfNotPresent
          command: ["python", "/app/app.py"]
          envFrom:
            - configMapRef: { name: minio-config }
            - secretRef:    { name: minio-secrets }
          env:
            - name: API_BASE
              value: "https://fakestoreapi.com"
