apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: ecommerce
type: Opaque
stringData:
  POSTGRES_USER: warehouse
  POSTGRES_PASSWORD: warehouse_pwd
  POSTGRES_DB: warehouse_db