ecommerce_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PG_HOST', 'localhost') }}"
      port: "{{ env_var('PG_PORT', '5432') | int }}"
      user: "{{ env_var('PG_USER', 'warehouse') }}"
      password: "{{ env_var('PG_PASSWORD', 'password') }}"
      dbname: "{{ env_var('PG_DB', 'warehouse_db') }}"
      schema: "{{ env_var('PG_SCHEMA', 'analytics') }}"
      threads: 4


env:
  - name: PG_HOST
    valueFrom: { secretKeyRef: { name: postgres-secrets, key: POSTGRES_HOST } }
  - name: PG_PORT
    valueFrom: { secretKeyRef: { name: postgres-secrets, key: POSTGRES_PORT } }
  - name: PG_USER
    valueFrom: { secretKeyRef: { name: postgres-secrets, key: POSTGRES_USER } }
  - name: PG_PASSWORD
    valueFrom: { secretKeyRef: { name: postgres-secrets, key: POSTGRES_PASSWORD } }
  - name: PG_DATABASE
    valueFrom: { secretKeyRef: { name: postgres-secrets, key: POSTGRES_DB } }
  - name: PG_SCHEMA
    valueFrom: { secretKeyRef: { name: postgres-secrets, key: POSTGRES_SCHEMA } }