services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "5433:5432"

  webserver:
    image: apache/airflow:2.10.2
    command: webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      KUBECONFIG: /opt/airflow/.kube/config
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8088:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 40
    volumes:
      - ./airflow-local/dags:/opt/airflow/dags:rw
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
      - $HOME/.kube:/opt/airflow/.kube:ro

  scheduler:
    image: apache/airflow:2.10.2
    command: scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__PARALLELISM: "8"
      AIRFLOW__CORE__DAG_CONCURRENCY: "8"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      KUBECONFIG: /opt/airflow/.kube/config
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./airflow-local/dags:/opt/airflow/dags:rw
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
      - $HOME/.kube:/opt/airflow/.kube:ro

volumes:
  airflow_logs: {}
  airflow_plugins: {}
