name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Build Docker images (hosted)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build images
        run: |
          docker build -t extractor:ci ./extractor
          docker build -t loader:ci    ./loader
          docker build -t exporter:ci  ./exporter
          # dbt-runner must be built from repo root so COPY dbt-runner/... works
          docker build -t dbt-runner:ci -f dbt-runner/Dockerfile .

  run-k8s-pipeline:
    name: Run full pipeline in K8s (self-hosted)
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4

      # Put profiles.yml into the cluster as a ConfigMap (idempotent)
      - name: Ensure dbt profiles ConfigMap exists
        run: |
          kubectl create configmap dbt-profiles \
            --from-file=profiles.yml=./dbt-runner/profiles.yml \
            -n ecommerce --dry-run=client -o yaml | kubectl apply -f -

      # Run your end-to-end pipeline (extractor -> loader -> dbt -> exporter)
      - name: Execute end-to-end pipeline
        env:
          NS: ecommerce
        run: |
          chmod +x scripts/rerun-all.sh
          NS=ecommerce ./scripts/rerun-all.sh
