name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run-pipeline:
    runs-on: ubuntu-latest
    name: Build and Run Data Pipeline
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r dbt-runner/requirements.txt || true

      - name: Verify dbt setup
        run: |
          dbt --version || echo "dbt not installed properly"
          ls -R dbt-runner || true

      - name: Run dbt commands
        env:
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PORT: ${{ secrets.PG_PORT }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_DB: ${{ secrets.PG_DB }}
        run: |
          cd dbt-runner
          dbt deps || true
          dbt debug || true
          dbt run

      - name: Run Kubernetes pipeline
        run: |
          chmod +x scripts/rerun-all.sh
          ./scripts/rerun-all.sh || echo "Kubernetes pipeline step skipped (local-only)"
