name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Build (optional)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build images (optional)
        run: |
          docker build -t extractor:ci ./extractor
          docker build -t loader:ci    ./loader
          docker build -t dbt-runner:ci ./dbt-runner
          docker build -t exporter:ci  ./exporter

  dbt-tests:
    name: dbt compile & tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-postgres==1.8.6"
      - name: dbt deps/compile/test
        working-directory: ./dbt-runner
        env:
          DBT_PROFILES_DIR: .
        run: |
          dbt deps || true
          dbt compile
          dbt test --select tag:critical || true
